spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: root
#security:
#  basic:
#    enabled: false

huzihan:
  security:
#    browserProperties:
#     loginPage: Demo-sigIn.html
#     loginType: REDIRECT
    validateCode:
      imageCode:
        length: 6
        width: 100
        urls: /user/*

